version: '3.8'

services:
  app:
    container_name: workout.server
    build:
      context: ./
    ports:
      - '${PORT}:${PORT}'
    env_file: .env
    environment:
      NODE_ENV: production
    volumes:
      - ./:/app
