version: '3.8'

services:
  app:
    container_name: workout.server
    build:
      context: ./
    ports:
      - '${PORT}:${PORT}'
    network_mode: host
    env_file: .env
    volumes:
      - ./:/app
